name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Verification step for 23f3004174@ds.study.iitm.ac.in"
        run: echo "This step confirms the workflow contains your email."

      - name: "Say Hello"
        run: echo "Hello, world! GitHub Actions is working ✅"
